version: '3.7'
services:
    cypress_test:
        image: cypress_compose
        build: 
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./dockerReports/:/app/cypress/reports/mocha
            - ./dockerReports/:/app/cypress/reports/mochareports    